package com.pouyaa.core.network.model.meal

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class NetworkMeal(
    @SerialName(value = "idMeal") val id: String?,
    @SerialName(value = "strMeal") val name: String?,
    @SerialName(value = "strMealThumb") val imageUrl: String?,
    @SerialName(value = "strCategory") val category: String?,
    @SerialName(value = "strArea") val nationality: String?,
    @SerialName(value = "strInstructions") val instructions: String?,
    @SerialName(value = "strSource") val source: String?,
    @SerialName(value = "strIngredient1") val ingredient1: String?,
    @SerialName(value = "strMeasure1") val measure1: String?,
    @SerialName(value = "strIngredient2") val ingredient2: String?,
    @SerialName(value = "strMeasure2") val measure2: String?,
    @SerialName(value = "strIngredient3") val ingredient3: String?,
    @SerialName(value = "strMeasure3") val measure3: String?,
    @SerialName(value = "strIngredient4") val ingredient4: String?,
    @SerialName(value = "strMeasure4") val measure4: String?,
    @SerialName(value = "strIngredient5") val ingredient5: String?,
    @SerialName(value = "strMeasure5") val measure5: String?,
    @SerialName(value = "strIngredient6") val ingredient6: String?,
    @SerialName(value = "strMeasure6") val measure6: String?,
    @SerialName(value = "strIngredient7") val ingredient7: String?,
    @SerialName(value = "strMeasure7") val measure7: String?,
    @SerialName(value = "strIngredient8") val ingredient8: String?,
    @SerialName(value = "strMeasure8") val measure8: String?,
    @SerialName(value = "strIngredient9") val ingredient9: String?,
    @SerialName(value = "strMeasure9") val measure9: String?,
    @SerialName(value = "strIngredient10") val ingredient10: String?,
    @SerialName(value = "strMeasure10") val measure10: String?,
    @SerialName(value = "strIngredient11") val ingredient11: String?,
    @SerialName(value = "strMeasure11") val measure11: String?,
    @SerialName(value = "strIngredient12") val ingredient12: String?,
    @SerialName(value = "strMeasure12") val measure12: String?,
    @SerialName(value = "strIngredient13") val ingredient13: String?,
    @SerialName(value = "strMeasure13") val measure13: String?,
    @SerialName(value = "strIngredient14") val ingredient14: String?,
    @SerialName(value = "strMeasure14") val measure14: String?,
    @SerialName(value = "strIngredient15") val ingredient15: String?,
    @SerialName(value = "strMeasure15") val measure15: String?,
    @SerialName(value = "strIngredient16") val ingredient16: String?,
    @SerialName(value = "strMeasure16") val measure16: String?,
    @SerialName(value = "strIngredient17") val ingredient17: String?,
    @SerialName(value = "strMeasure17") val measure17: String?,
    @SerialName(value = "strIngredient18") val ingredient18: String?,
    @SerialName(value = "strMeasure18") val measure18: String?,
    @SerialName(value = "strIngredient19") val ingredient19: String?,
    @SerialName(value = "strMeasure19") val measure19: String?,
    @SerialName(value = "strIngredient20") val ingredient20: String?,
    @SerialName(value = "strMeasure20") val measure20: String?
)
